main: com.brandontm.regionwarp.RegionWarp
name: RegionWarp
version: 0.1
api-version: 1.15

depend: [WorldGuard]

commands:
  regionWarp:
    description: Set or remove region warp point
    usage: /regionwarp <set|remove> <regionName> [description...]
    aliases: [rw]
    permission: regionwarp.warp.modify
    permission-message: No tienes permiso para user este comando
  test:
    description: Test command
    usage: /test

permissions:
  regionwarp.warp.modify:
    description: Set or remove region warp points
    default: op