main: com.brandontm.regionwarp.RegionWarp
name: RegionWarp
version: 0.1

depend: [WorldGuard]

commands:
  regionWarp:
    description: Set or remove region warp point
    usage: /regionwarp <set|remove> <regionName>
    aliases: [rw]
    permission: regionwarp.warp.modify
    permission-message: No tienes permiso para user este comando

permissions:
  regionwarp.warp.modify:
    description: Set or remove region warp points
    default: op