main: com.brandontm.regionwarp.RegionWarp
name: RegionWarp
version: 0.1
api-version: 1.15

depend: [WorldGuard]

commands:
  regionWarp:
    description: Set or remove region warp point
    usage: /regionwarp <set|remove> <regionName> [description...]
    aliases: [rw]
    permission: regionwarp.warp.modify
    permission-message: No tienes permiso para user este comando

permissions:
  regionwarp.warp.use:
    description: Warp player to region
    default: true
  regionwarp.warp.modify:
    description: Set or remove region warp points
    default: op
  regionwarp.warp.*:
    description: All warp permissions
    default: op
    children:
      regionwarp.warp.use: true
      regionwarp.warp.modify: true

  regionwarp.signs.create:
    description: Create region warp sign
    default: op
  regionwarp.signs.remove:
    description: Create region warp sign
    default: op
  regionwarp.signs.*:
    description: All signs permissions
    default: op
    children:
      regionwarp.signs.create: true
      regionwarp.signs.remove: true
